### PR TITLE
set partitionId/contextentry to base64 dn: dc=openmicroscopy,dc=org d…

### PR DESCRIPTION
**Pull request by CSchemmy**
Solve the problem of missing Domain from partition

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks for the fix, @CSchemmy. I've added a commit to see if Travis will turn green.

**Comment by joshmoore** [comment]
@pwalczysko : note that this will be considered a breaking change since the scripts available in master will no longer work and vice versa.

**Comment by CSchemmy** [comment]
Without the change, the configuration is simply not faulty

**Comment by joshmoore** [comment]
@CSchemmy : sorry, I don't understand. You're saying the image was not working for you?

**Comment by CSchemmy** [comment]
When I connect to the container with ApacheStudio the partition is configured but is missing on the left side

**Comment by joshmoore** [comment]
Aha. I tend to use the CLI (namely the scripts under `bin/`). Before your change, the scripts all manually created `dc=openmicroscopy,dc=org` so I never noticed the fact that the partition was missing.

**Comment by CSchemmy** [comment]
I am currently working on LDAP and find Apache Directory Studio a good tool to learn

**Comment by joshmoore** [comment]
Are you running Apache DS via this docker container or just using the configuration files?

**Comment by CSchemmy** [comment]
I have install Apache Studio and the Container is Run in the cloud. I am currently working on a solution for the certificate and the free choice of the domain. Then the image would be universally usable in the clouwd. The configuration would then be done via ldaps. The scripts in /bin are only helpful if you use them locally and do not want to work with Apache Directory Studio

**Comment by joshmoore** [comment]
> I am currently working on a solution for the certificate and the free choice of the domain. 

Sounds great. Keep us posted.

**Comment by pwalczysko** [comment]
@joshmoore Re https://github.com/openmicroscopy/apacheds-docker/pull/8#issuecomment-365841655 

  1. if the scripts in master, namely ``ldapmanager`` stop to work, then this is a blocker for me and there is a clear no from my side here, sorry
  2. what do you mean by ``vice versa`` ?

**Comment by CSchemmy** [comment]
I will test it tonight. but I think it will work.

**Comment by joshmoore** [comment]
@pwalczysko : The change here means that when you create an `openmicroscopy/apacheds` docker container it already has the `dc=openmicroscopy,dc=org` base present. It no longer needs to be created, and attempts to do so fail. Similarly, on `clear`, it _shouldn't_ be deleted:

|                         | 0.3.0 server                                                                    | 0.4.0 server (this PR)                                                                         |
|-------------------------|---------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| 0.3.0 scripts           | :+1:                                                                            | `init` fails when they try to create the base; `clear` the base leading to failures downstream |
| 0.4.0 scripts (this PR) | Fail on most commands since there is no base; `clear` leaves the base dangling. | :+1:                                                                                           |

**Comment by CSchemmy** [comment]
Thanks

**Comment by pwalczysko** [comment]
@joshmoore that https://github.com/openmicroscopy/apacheds-docker/pull/8#issuecomment-365881128 looks good, thank you

**Review by joshmoore — APPROVED** [review]
Releasing as 0.4.0 to Docker Hub

**Comment by joshmoore** [comment]
Currently building on Hub: https://hub.docker.com/r/openmicroscopy/apacheds/builds/

Thanks again @CSchemmy !

**Pull request merged**
